package fr.snake.ui;

import fr.snake.Settings;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;

public class SettingsDialog {
    private JButton OKButton;
    private JPanel panel1;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;

    private Settings settings;

    public SettingsDialog(Settings settings) {
        this.settings = settings;
        OKButton.addActionListener((e) -> ok());
        textField1.setText(String.valueOf(settings.getDefaultSnakeLength()));
        textField2.setText(String.valueOf(settings.getDefaultBodyWidth()));
        textField3.setText(String.valueOf(settings.getMinimumFoods()));
        textField4.setText(String.valueOf(settings.getMaximumFoods()));
        textField5.setText(String.valueOf(settings.getMinimumSnakes()));
    }

    public void ok() {
        try {
            settings.setDefaultSnakeLength(Integer.parseInt(textField1.getText()));
            settings.setDefaultBodyWidth(Integer.parseInt(textField2.getText()));
            settings.setMinimumFoods(Integer.parseInt(textField3.getText()));
            settings.setMaximumFoods(Integer.parseInt(textField4.getText()));
            settings.setMinimumSnakes(Integer.parseInt(textField5.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "L'une des valeurs est invalide", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        try {
            settings.save(new File("settings.json"));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erreur lors de la sauvegarde des paramètres", "Attention", JOptionPane.WARNING_MESSAGE);
        }
        ((JFrame) this.panel1.getParent().getParent().getParent()).setVisible(false);
    }

    public static void launch(Settings settings) {
        JFrame frame = new JFrame("Paramètres");
        frame.setContentPane(new SettingsDialog(settings).panel1);
        frame.pack();
        frame.setSize(800, 600);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        OKButton = new JButton();
        OKButton.setText("OK");
        panel1.add(OKButton, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Longueur du serpent par défaut");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 50;
        panel2.add(textField1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Largeur du serpent par défaut");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Minimum de nourriture");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Maximum de nourriture");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Minimum de serpents IA");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label5, gbc);
        textField3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField3, gbc);
        textField4 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField4, gbc);
        textField5 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField5, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
